name: "test"
on:
  push:
    # tags: ["v[0-9]+.[0-9]+.[0-9]+*"]
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: 1.92.0

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - name: setup node
        uses: actions/setup-node@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
      - name: install target
        run: |
          rustup update
          rustup target add aarch64-apple-darwin
      - name: rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: macos-build
      - name: release
        run: |
          cargo install cargo-bundle
          cargo bundle --release  --features mimalloc
          mv target/release/bundle/osx/Zedis.app .
      - name: create dmg
        run: |
          brew install create-dmg
          create-dmg \
            --volname "Zedis Installer" \
            --window-pos 200 120 \
            --window-size 600 400 \
            --icon-size 100 \
            --icon "Zedis.app" 175 190 \
            --hide-extension "Zedis.app" \
            --app-drop-link 425 185 \
            "Zedis-aarch64.dmg" \
            "Zedis.app"
      - name: upload asset
        run: |
          ./.github/workflows/upload_asset.sh ./Zedis-aarch64.dmg $GITHUB_TOKEN

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - name: setup node
        uses: actions/setup-node@v6
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          target: x86_64-pc-windows-msvc
      - name: rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: windows-build
      - name: release
        run: |
          cargo build --release  --features mimalloc
          mv target/release/zedis.exe ./zedis.exe
      - name: zip
        shell: powershell
        run: |
          ls .
          Compress-Archive -Path zedis.exe -Destination zedis-windows.exe.zip
      - name: upload asset
        shell: bash
        run: |
          ./.github/workflows/upload_asset.sh ./zedis-windows.exe.zip $GITHUB_TOKEN
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: setup node
        uses: actions/setup-node@v6
      - name: Install Linux Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev libxkbcommon-x11-dev libssl-dev
      - name: install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          target: x86_64-unknown-linux-gnu
      - name: rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: linux-build
      - name: release
        run: |
          cargo build --release  --features mimalloc
          ls -lh target/release
          mv target/release/zedis ./zedis
          tar -czvf zedis-linux-x86_64.tar.gz zedis
      - name: upload asset
        run: |
          ./.github/workflows/upload_asset.sh ./zedis-linux-x86_64.tar.gz $GITHUB_TOKEN
